packages:
  # all packages in subdirs of packages/ and components/
  - 'packages/*'
  # - 'components/**'
  # # exclude packages that are inside test directories
  # - '!**/test/**'
allowBuilds:
  '@parcel/watcher': true
minimumReleaseAgeExclude:
  - '@types/mithril@2.2.9'
  - mithril-ui-form@2.3.0
  - slimdown-js@1.5.0
